### ISSUE TITLE
Bypass JP6

### ISSUE THREAD

**Issue by Sedrickgates** [arananet/LAZARUSTORM#1]
Hi,
First of all, great work and thank you for making this possible. I do not have the skills (yet) to make things like this a reality. 
Now I'm skilled to build those things and I have recently built 20 of them I'm planning to dell to the Amiga community through the FB groups PiStorm,  Commodore Amiga and the French group Amiga forever and beyond. I don't take a large margin (24€ a pop) as I like to help the community I'm part of.
Now the big question : How did you make the JP6 bridging optional? I'm OK to hear that you don't want to disclose it of course but I'd be sad.
I'm curious and also would like to know if it can be easily patch on the already built boards?
Are you adding a pin, a wire and a quick clamp to pin 15 or another location on the board? (that would be impractical but no solder required
Are you taking another signal from the bus and drive a CLK signal from it?

Again I'm not in to make a fortune and really curious about the way it's done.

Thanks
Cédric

**Comment by arananet** [comment]
jp6 is not optional, some revs have it directly and those who has not, needs to solder the jp6 by bridge with a solder join.

If you are taking profit of what i'm sharing, at least donate some of this profit to an ONG.
