### ISSUE TITLE
Jumper Settings

### ISSUE THREAD

**Issue by SilverRat** [arananet/LAZARUSTORM#2]
Hi, I'm not familiar with the VPA and BR jumpers.  Could you share what these jumpers do, and how one would go about determining the best configuration for a machine?  It seems like everyone is jumping 2-3 on the VPA, but the BR is sometimes open, sometimes closed.  

Thanks,
Jerry

**Comment by pjaegerhh** [comment]
Hi Jerry - same question here. Did you get it running in your Amiga ? How does your JP6 Pin look like :) (see also my raised issue). Best Peter

**Comment by SilverRat** [comment]
Hi Peter.  I did get the Lazarustorm working on my Rev5 and Rev6 A500 machines.  The BR jumper did not seem to make any difference on how it functions on either machine.  I did not change the VPA jumper, I left that jumped between 2-3 on all tests. 

But I do have some issues.  On the Rev5 board, it will NOT work with the CPU in the socket. I have to remove it to work.  So it kindof defeats the whole purpose.  

On the Rev6 board, it works fine with the CPU in socket (regardless of the BR jumper setting) with one annoying behavior specific to my machine. I have a dual ROM selector which has a speaker that beeps when selecting a different kickstart. With the Lazarustorm connected, that speaker beeps continuously from the time I turn on the machine until the PiStorm starts. Then the beeb stops.

I did not take a picture of the JP6 jumper, but I know it's confusing as there is a pad to the right and below the JP6 labeled pad.  I jumped to the one BELOW.

**Comment by pjaegerhh** [comment]
ok. Thanks Jerry. Actually I tried a few Revisions. Currently I'm running the pistorm on a Rev5 in the 68k socket. works like a charm. Will try to put it in the LS again but this config would not add any benefits as you wrote. Let's see. My Rev6 Boards all have a ROM selector. Maybe it's smart to remove it.

**Comment by SilverRat** [comment]
One more point of clarification. To make the Lazarustorm work on my Rev5, I have to manually patch the clock signal to the Lazarus storm . . . NOT a great solution.  I soldered a wire on the storm card itself, pulled the CPU, and put a singe "Pin" into pin15 on the CPU socket (15th from the bottom right) in order to get the clock signal to the card.  This is where it gets weird.   I then tried a patch cable on the board. I soldered to the bottom on Pin 15 on the CPU socket and soldered to the gold pad on the expansion port (pin 4 I believe . . . It's labeled on the Lazarusstorm card).  And that patch wire DID NOT WORK!!!!!  So on my Rev 5, it's sitting the in CPU socket at the moment.  No the solution I hoped for.

**Comment by arananet** [comment]
Basically, those revisions that does not have connected the clock signal, requires to solder the jp6 bridge to expose the clock signal externally, you don't need to put a wire.. that's what the jp6 jumper do.

About the jumpers, it always needs to be set, why? because is the way that the adapter takes priority on the bus, shutting down the internal cpu and allowing the external to work. Of course there are accerelators that does not have even the BR signal connected, because were designed to use lonely in the bus. Aka V500 rev 2. Not having the jp6 on your a500 motherboard is not a problem of this adapter. It just that your motherboard revision does not have it.
