### ISSUE TITLE
JP6 unclear

### ISSUE THREAD

**Issue by pjaegerhh** [arananet/LAZARUSTORM#3]
For me it is still super unclear if the 2 "pins" of JP6 need to be soldered or if the lower pin just need to be closed with soldering tin and both are not connected. I'm actually using different Amiga Version (one is a Rev.6A) but for whatever reason I don't get it to work while the PiStorm as such is working perfectly fine in the 68k socket...

**Comment by NemoN** [comment]
Same issue here with Rev.6A - PiStorm inside 64k socket works, but in the Lazarustorm not.

**Comment by SilverRat** [comment]
I could not get this to work without Jumping JP6.  Just a solder blob between the pad just below the JP6 label on the board and the second pad beneath it.  There was a pad to the right of the JP6 pads.  I did NOT jump to that point. I jumped 2-3 on the VPA on the Lazarustorm.  The BR jumper did not seem to matter.

**Comment by pjaegerhh** [comment]
thank you @SilverRat . I'll give it another try next weekend. Would add tremedous amount of clarity if the pictures would show how it should look like and not only where the jumper is from my perspective. Also it would be helpful to explain the other jumpers on Lazarustorm

**Comment by arananet** [comment]
jp6 is well documented on the readme of this project, you should follow the instructions. If your board revision does not even have that option, is not a problem of the adapter but the a500 motherboard itself.
